# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Python Programming for Math
author:  Marty Weissman and Suzana Șerboi
logo: content/img/logo-python-4-math.png
copyright: "2024"

requirements:
  - sympy
  - matplotlib
  - numpy

# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "cache"


# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default    

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ssuzana/python-programming-for-math  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon                     : 'content/img/logo.png'
  home_page_in_navbar         : false
  use_edit_page_button        : true
  extra_footer: |
    <div>
         <div style="text-align: left;">Powered by <a href="https://jupyterbook.org">Jupyter Book</a></div>
    </div>

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :   # A list of extra extensions to load by Sphinx (added to those already used by JB).
  local_extensions          :   # A list of local extensions to load by sphinx specified by "name: path" items
  recursive_update          : false # A boolean indicating whether to overwrite the Sphinx config (true) or recursively update (false)

    